FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# restalam

Polls is a simple API allowing consumers to view polls and vote in them.


### Create a New User [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "usuario": "Favourite programming language?",
            "password":"askldasldjasdjhasd"
        }

+ Response 200 (application/json)

    + Headers

            CORS: localhost

    + Body

            {
                "status":"200",
                "message":"El usuario ha sido guardado"
            }